# Generated by Django 4.0.3 on 2022-04-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
                ('tracks_in_album', models.IntegerField()),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=650)),
                ('followers', models.IntegerField()),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.country')),
            ],
            options={
                'db_table': 'popularity',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('uri', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
                ('danceability', models.FloatField(null=True)),
                ('energy', models.FloatField(null=True)),
                ('key', models.IntegerField(null=True)),
                ('loudness', models.FloatField(null=True)),
                ('mode', models.BooleanField(null=True)),
                ('speechiness', models.FloatField(null=True)),
                ('acoustics', models.FloatField(null=True)),
                ('instrumentalness', models.FloatField(null=True)),
                ('liveness', models.FloatField(null=True)),
                ('valence', models.FloatField(null=True)),
                ('tempo', models.FloatField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('track_number_album', models.IntegerField(null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.album')),
                ('country_track', models.ManyToManyField(through='WebApp.Popularity', to='WebApp.country')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.genre')),
            ],
            options={
                'db_table': 'track',
            },
        ),
        migrations.AddField(
            model_name='popularity',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.track'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.artist'),
        ),
    ]
